#!/usr/bin/env python
"""Convert an exported temporal external dataset to nnU-Net imagesTs/labelsTs.

Input layout:
  external_dir/
    npz/*.npz                  each contains image and mask arrays [D,H,W]
    slice_manifest.csv         metadata generated by export/subset scripts

Output layout:
  output_dir/
    imagesTs/<case_id>_0000.nii.gz
    labelsTs/<case_id>.nii.gz
    dataset.json
    manifest.json
    prepare_summary.json

This script does not decode DICOM or change labels. It is only a format bridge
so the external set can be passed through the already trained nnU-Net model.
"""

from __future__ import annotations

import argparse
import csv
import json
import shutil
from collections import Counter
from pathlib import Path
from typing import Any

import numpy as np
from tqdm import tqdm


def require_nibabel():
    try:
        import nibabel as nib
    except ImportError as exc:
        raise SystemExit("nibabel is required. Install it with: pip install nibabel") from exc
    return nib


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def save_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)


def load_npz(path: Path) -> tuple[np.ndarray, np.ndarray]:
    data = np.load(path)
    if "image" not in data.files or "mask" not in data.files:
        raise ValueError(f"{path} must contain image and mask arrays; got keys={data.files}")
    image = data["image"]
    mask = data["mask"]
    if image.ndim != 3 or mask.ndim != 3:
        raise ValueError(f"{path} image/mask must be 3D [D,H,W]; got image={image.shape}, mask={mask.shape}")
    if image.shape != mask.shape:
        raise ValueError(f"{path} image/mask shape mismatch: image={image.shape}, mask={mask.shape}")
    return image.astype(np.float32), (mask > 0).astype(np.uint8)


def to_nnunet_xyz(volume_dhw: np.ndarray) -> np.ndarray:
    return np.transpose(volume_dhw, (2, 1, 0))


def case_id_from_npz(path: Path) -> str:
    return path.stem


def collect_case_metadata(slice_manifest: Path) -> dict[str, dict[str, Any]]:
    metadata: dict[str, dict[str, Any]] = {}
    if not slice_manifest.exists():
        return metadata
    rows = read_csv(slice_manifest)
    for row in rows:
        case_id = row.get("case_id", "").strip()
        if not case_id or case_id in metadata:
            continue
        metadata[case_id] = {
            "case_id": case_id,
            "patient_id": row.get("patient_id", ""),
            "label": row.get("label", ""),
            "seq": row.get("seq", ""),
            "series_uid": row.get("series_uid", ""),
            "series_description": row.get("series_description", ""),
            "label_source": row.get("label_source", ""),
            "label_path": row.get("label_path", ""),
            "mask_transform": row.get("mask_transform", ""),
            "source_npz_path": row.get("npz_path", ""),
        }
    return metadata


def write_dataset_json(output_dir: Path, dataset_id: int, dataset_name: str, num_test: int) -> None:
    dataset_json = {
        "channel_names": {"0": "MRI"},
        "labels": {"background": 0, "lesion": 1},
        "numTraining": 0,
        "numTest": num_test,
        "file_ending": ".nii.gz",
        "dataset_name": dataset_name,
        "overwrite_image_reader_writer": "NibabelIO",
        "description": "Temporal external spinal lesion segmentation test set converted from exported npz volumes.",
        "reference": "",
        "licence": "",
        "release": "0.1",
        "dataset_id": dataset_id,
    }
    save_json(output_dir / "dataset.json", dataset_json)


def prepare(args: argparse.Namespace) -> None:
    nib = require_nibabel()
    external_dir = Path(args.external_dir).resolve()
    output_dir = Path(args.output_dir).resolve()

    if output_dir.exists() and args.overwrite:
        shutil.rmtree(output_dir)
    if output_dir.exists():
        raise FileExistsError(f"Output directory already exists: {output_dir}. Use --overwrite to replace it.")

    images_ts = output_dir / "imagesTs"
    labels_ts = output_dir / "labelsTs"
    images_ts.mkdir(parents=True, exist_ok=True)
    labels_ts.mkdir(parents=True, exist_ok=True)

    npz_dir = external_dir / "npz"
    npz_paths = sorted(npz_dir.glob("*.npz"))
    if not npz_paths:
        raise FileNotFoundError(f"No npz files found in {npz_dir}")

    metadata = collect_case_metadata(external_dir / "slice_manifest.csv")
    affine = np.diag([1.0, 1.0, 1.0, 1.0])
    manifest = []
    counts = Counter()
    failures = []

    for npz_path in tqdm(npz_paths, desc="Convert external npz to nnU-Net imagesTs", ncols=120):
        case_id = case_id_from_npz(npz_path)
        try:
            image, mask = load_npz(npz_path)
            image_nifti = nib.Nifti1Image(to_nnunet_xyz(image), affine)
            mask_nifti = nib.Nifti1Image(to_nnunet_xyz(mask).astype(np.uint8), affine)
            nib.save(image_nifti, images_ts / f"{case_id}_0000.nii.gz")
            nib.save(mask_nifti, labels_ts / f"{case_id}.nii.gz")
        except Exception as exc:
            failures.append({"case_id": case_id, "npz_path": str(npz_path), "error": str(exc)})
            continue

        item = dict(metadata.get(case_id, {}))
        item.update(
            {
                "case_id": case_id,
                "split": "external_test",
                "npz_path": str(npz_path),
                "image_nii": str(images_ts / f"{case_id}_0000.nii.gz"),
                "label_nii": str(labels_ts / f"{case_id}.nii.gz"),
                "shape_dhw": list(image.shape),
                "mask_voxels": int(mask.sum()),
            }
        )
        manifest.append(item)
        counts["cases"] += 1
        if item.get("label"):
            counts[f"label_{item['label']}"] += 1
        if item.get("seq"):
            counts[f"seq_{item['seq']}"] += 1

    dataset_name = f"Dataset{args.dataset_id:03d}_{args.dataset_name}"
    write_dataset_json(output_dir, args.dataset_id, dataset_name, len(manifest))
    save_json(output_dir / "manifest.json", manifest)
    save_json(output_dir / "failed_cases.json", failures)

    summary = {
        "external_dir": str(external_dir),
        "output_dir": str(output_dir),
        "dataset": dataset_name,
        "dataset_id": args.dataset_id,
        "dataset_name": args.dataset_name,
        "num_npz_files": len(npz_paths),
        "num_converted_cases": len(manifest),
        "num_failed_cases": len(failures),
        "counts": dict(counts),
        "imagesTs": str(images_ts),
        "labelsTs": str(labels_ts),
        "manifest": str(output_dir / "manifest.json"),
        "dataset_json": str(output_dir / "dataset.json"),
        "note": "External test only: imagesTs/labelsTs are written; imagesTr/labelsTr are intentionally absent.",
    }
    save_json(output_dir / "prepare_summary.json", summary)
    print(json.dumps(summary, ensure_ascii=False, indent=2))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Convert exported temporal external npz volumes to nnU-Net test format.")
    parser.add_argument("--external_dir", required=True)
    parser.add_argument("--output_dir", required=True)
    parser.add_argument("--dataset_id", type=int, default=504)
    parser.add_argument("--dataset_name", default="SpinalLesionTemporalExternal")
    parser.add_argument("--overwrite", action="store_true")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    prepare(args)


if __name__ == "__main__":
    main()
